import PptxGenJS from "pptxgenjs";
import type { Idea } from "./types";

// VoltEdge brand colors
const BLUE = "2251FF";
const INK = "0D1117";
const NEUTRAL = "5A6570";
const WHITE = "FFFFFF";
const LIGHT_BG = "F5F7FA";

export async function generatePatentPptx(idea: Idea): Promise<Blob> {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "VoltEdge Patent Platform";
  pptx.title = idea.title || "Invention Disclosure";

  // Slide 1: Title
  let slide = pptx.addSlide();
  slide.background = { color: INK };
  slide.addText(idea.title || "Invention Disclosure", {
    x: 0.8,
    y: 1.5,
    w: 11.5,
    h: 1.5,
    fontSize: 36,
    bold: true,
    color: WHITE,
    fontFace: "Arial",
  });
  slide.addText("Invention Disclosure Presentation", {
    x: 0.8,
    y: 3.2,
    w: 11.5,
    h: 0.5,
    fontSize: 18,
    color: BLUE,
    fontFace: "Arial",
  });
  slide.addText(`Generated by VoltEdge — ${new Date().toLocaleDateString()}`, {
    x: 0.8,
    y: 6.5,
    w: 11.5,
    h: 0.3,
    fontSize: 10,
    color: NEUTRAL,
    fontFace: "Arial",
  });

  // Slide 2: Problem Statement
  if (idea.problemStatement) {
    slide = pptx.addSlide();
    slide.addText("Problem Statement", {
      x: 0.8,
      y: 0.5,
      w: 11.5,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: INK,
      fontFace: "Arial",
    });
    slide.addText(idea.problemStatement, {
      x: 0.8,
      y: 1.6,
      w: 11.5,
      h: 4,
      fontSize: 16,
      color: NEUTRAL,
      fontFace: "Arial",
      valign: "top",
    });
  }

  // Slide 3: Existing Approach
  if (idea.existingApproach) {
    slide = pptx.addSlide();
    slide.addText("Existing Approach & Limitations", {
      x: 0.8,
      y: 0.5,
      w: 11.5,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: INK,
      fontFace: "Arial",
    });
    slide.addText(idea.existingApproach, {
      x: 0.8,
      y: 1.6,
      w: 11.5,
      h: 4,
      fontSize: 16,
      color: NEUTRAL,
      fontFace: "Arial",
      valign: "top",
    });
  }

  // Slide 4: Proposed Solution
  if (idea.proposedSolution) {
    slide = pptx.addSlide();
    slide.addText("Proposed Solution", {
      x: 0.8,
      y: 0.5,
      w: 11.5,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: INK,
      fontFace: "Arial",
    });
    slide.addText(idea.proposedSolution, {
      x: 0.8,
      y: 1.6,
      w: 11.5,
      h: 4,
      fontSize: 16,
      color: NEUTRAL,
      fontFace: "Arial",
      valign: "top",
    });
  }

  // Slide 5: Technical Architecture
  if (idea.technicalApproach) {
    slide = pptx.addSlide();
    slide.addText("Technical Architecture", {
      x: 0.8,
      y: 0.5,
      w: 11.5,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: INK,
      fontFace: "Arial",
    });
    slide.addText(idea.technicalApproach, {
      x: 0.8,
      y: 1.6,
      w: 11.5,
      h: 4,
      fontSize: 14,
      color: NEUTRAL,
      fontFace: "Arial",
      valign: "top",
    });
    if (idea.techStack?.length > 0) {
      slide.addText(`Tech Stack: ${idea.techStack.join(" \u2022 ")}`, {
        x: 0.8,
        y: 6,
        w: 11.5,
        h: 0.4,
        fontSize: 11,
        color: BLUE,
        fontFace: "Arial",
      });
    }
  }

  // Slide 6: Inventive Step(s)
  if (idea.inventiveStepAnalysis) {
    slide = pptx.addSlide();
    slide.addText("Inventive Step(s)", {
      x: 0.8,
      y: 0.5,
      w: 11.5,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: INK,
      fontFace: "Arial",
    });
    slide.addShape(pptx.ShapeType.roundRect, {
      x: 0.8,
      y: 1.5,
      w: 11.5,
      h: 1.5,
      fill: { color: LIGHT_BG },
      rectRadius: 0.1,
    });
    slide.addText(idea.inventiveStepAnalysis.primaryInventiveStep, {
      x: 1,
      y: 1.6,
      w: 11,
      h: 1.2,
      fontSize: 14,
      color: INK,
      fontFace: "Arial",
      bold: true,
      valign: "top",
    });
    slide.addText(
      `Technical Advantage: ${idea.inventiveStepAnalysis.technicalAdvantage}`,
      {
        x: 0.8,
        y: 3.3,
        w: 11.5,
        h: 1.5,
        fontSize: 13,
        color: NEUTRAL,
        fontFace: "Arial",
        valign: "top",
      }
    );
    if (idea.inventiveStepAnalysis.differentiatingFactors?.length > 0) {
      const factors = idea.inventiveStepAnalysis.differentiatingFactors
        .map((f: string) => `\u2022 ${f}`)
        .join("\n");
      slide.addText("Differentiating Factors:\n" + factors, {
        x: 0.8,
        y: 5,
        w: 11.5,
        h: 2,
        fontSize: 12,
        color: NEUTRAL,
        fontFace: "Arial",
        valign: "top",
      });
    }
  }

  // Slide 7: Patent Readiness Score
  if (idea.score) {
    slide = pptx.addSlide();
    slide.addText("Patent Readiness Score", {
      x: 0.8,
      y: 0.5,
      w: 11.5,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: INK,
      fontFace: "Arial",
    });
    const scores = [
      { label: "Inventive Step", value: idea.score.inventiveStep },
      { label: "Defensibility", value: idea.score.defensibility },
      { label: "Product Fit", value: idea.score.productFit },
    ];
    scores.forEach((s, i) => {
      const x = 0.8 + i * 4;
      slide.addShape(pptx.ShapeType.roundRect, {
        x,
        y: 2,
        w: 3.5,
        h: 3,
        fill: { color: LIGHT_BG },
        rectRadius: 0.1,
      });
      slide.addText(s.label, {
        x,
        y: 2.2,
        w: 3.5,
        h: 0.5,
        fontSize: 14,
        bold: true,
        color: INK,
        fontFace: "Arial",
        align: "center",
      });
      slide.addText(`${s.value}/3`, {
        x,
        y: 3,
        w: 3.5,
        h: 1.2,
        fontSize: 42,
        bold: true,
        color: BLUE,
        fontFace: "Arial",
        align: "center",
      });
    });
  }

  // Slide 8: Alice/101 Analysis
  if (idea.aliceScore) {
    slide = pptx.addSlide();
    slide.addText("Alice/Section 101 Analysis", {
      x: 0.8,
      y: 0.5,
      w: 11.5,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: INK,
      fontFace: "Arial",
    });
    const riskColor =
      idea.aliceScore.abstractIdeaRisk === "low"
        ? "2E6F4E"
        : idea.aliceScore.abstractIdeaRisk === "medium"
          ? "C69214"
          : "7A2E2E";
    slide.addText(`Score: ${idea.aliceScore.overallScore}/100`, {
      x: 0.8,
      y: 1.5,
      w: 5,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: BLUE,
      fontFace: "Arial",
    });
    slide.addText(`Risk Level: ${idea.aliceScore.abstractIdeaRisk.toUpperCase()}`, {
      x: 6,
      y: 1.5,
      w: 6,
      h: 0.6,
      fontSize: 20,
      bold: true,
      color: riskColor,
      fontFace: "Arial",
    });
    slide.addText(idea.aliceScore.practicalApplication, {
      x: 0.8,
      y: 2.5,
      w: 11.5,
      h: 2,
      fontSize: 13,
      color: NEUTRAL,
      fontFace: "Arial",
      valign: "top",
    });
  }

  // Slide 9: Market Opportunity
  if (idea.marketNeedsAnalysis) {
    slide = pptx.addSlide();
    slide.addText("Market Opportunity", {
      x: 0.8,
      y: 0.5,
      w: 11.5,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: INK,
      fontFace: "Arial",
    });
    slide.addText(idea.marketNeedsAnalysis.marketSize, {
      x: 0.8,
      y: 1.5,
      w: 11.5,
      h: 1.2,
      fontSize: 14,
      color: INK,
      fontFace: "Arial",
      bold: true,
      valign: "top",
    });
    slide.addText(idea.marketNeedsAnalysis.commercializationPotential, {
      x: 0.8,
      y: 3,
      w: 11.5,
      h: 1.5,
      fontSize: 13,
      color: NEUTRAL,
      fontFace: "Arial",
      valign: "top",
    });
    slide.addText(`Strategic Value: ${idea.marketNeedsAnalysis.strategicValue}`, {
      x: 0.8,
      y: 4.8,
      w: 11.5,
      h: 1.5,
      fontSize: 12,
      color: NEUTRAL,
      fontFace: "Arial",
      valign: "top",
    });
  }

  // Slide 10: Claims
  if (idea.claimDraft) {
    slide = pptx.addSlide();
    slide.addText("Claim Strategy", {
      x: 0.8,
      y: 0.5,
      w: 11.5,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: INK,
      fontFace: "Arial",
    });
    slide.addText("Method Claim (Independent)", {
      x: 0.8,
      y: 1.5,
      w: 11.5,
      h: 0.4,
      fontSize: 14,
      bold: true,
      color: BLUE,
      fontFace: "Arial",
    });
    slide.addText(idea.claimDraft.methodClaim.substring(0, 500), {
      x: 0.8,
      y: 2,
      w: 11.5,
      h: 2,
      fontSize: 11,
      color: NEUTRAL,
      fontFace: "Arial",
      valign: "top",
    });
    slide.addText("System Claim / CRM Claim", {
      x: 0.8,
      y: 4.2,
      w: 11.5,
      h: 0.4,
      fontSize: 14,
      bold: true,
      color: BLUE,
      fontFace: "Arial",
    });
    slide.addText(
      "See full invention disclosure document for complete claim language.",
      {
        x: 0.8,
        y: 4.8,
        w: 11.5,
        h: 0.5,
        fontSize: 12,
        color: NEUTRAL,
        fontFace: "Arial",
      }
    );
  }

  // Slide 11: Next Steps
  slide = pptx.addSlide();
  slide.addText("Next Steps", {
    x: 0.8,
    y: 0.5,
    w: 11.5,
    h: 0.8,
    fontSize: 28,
    bold: true,
    color: INK,
    fontFace: "Arial",
  });
  const nextSteps = idea.patentReport?.nextSteps || [
    "Complete internal review of invention disclosure",
    "Conduct comprehensive prior art search",
    "Engage patent counsel for patentability opinion",
    "Draft provisional patent application",
    "File provisional application with USPTO",
  ];
  nextSteps.forEach((step: string, i: number) => {
    slide.addText(`${i + 1}. ${step}`, {
      x: 0.8,
      y: 1.5 + i * 0.6,
      w: 11.5,
      h: 0.5,
      fontSize: 14,
      color: i < 2 ? INK : NEUTRAL,
      fontFace: "Arial",
    });
  });

  const blob = (await pptx.write({ outputType: "blob" })) as Blob;
  return blob;
}
