import { Document, Paragraph, HeadingLevel, TextRun, Packer, AlignmentType } from "docx";
import type { Idea } from "./types";

export async function generatePatentDocx(idea: Idea): Promise<Blob> {
  // Helper for creating styled paragraphs
  const heading1 = (text: string) =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 200 } });
  const heading2 = (text: string) =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 150 } });
  const bodyText = (text: string) =>
    new Paragraph({ text, spacing: { after: 120 }, style: "Normal" });
  const bulletPoint = (text: string) =>
    new Paragraph({ text, bullet: { level: 0 }, spacing: { after: 60 } });

  const children: Paragraph[] = [
    // Title
    new Paragraph({
      children: [new TextRun({ text: idea.title || "Untitled Invention", bold: true, size: 36 })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: "Invention Disclosure Document", italics: true, size: 24 })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by VoltEdge — ${new Date().toLocaleDateString()}`,
          size: 20,
          color: "666666",
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),
  ];

  // 1. Field of the Invention
  if (idea.techStack?.length > 0) {
    children.push(heading1("Field of the Invention"));
    children.push(
      bodyText(
        `The present invention relates to ${idea.techStack.join(", ")}. More particularly, the invention relates to ${idea.proposedSolution?.substring(0, 200) || "a novel technical approach"}.`
      )
    );
  }

  // 2. Background
  if (idea.problemStatement) {
    children.push(heading1("Background of the Invention"));
    children.push(bodyText(idea.problemStatement));
    if (idea.existingApproach) {
      children.push(bodyText("Existing approaches include: " + idea.existingApproach));
    }
  }

  // 3. Summary
  if (idea.proposedSolution) {
    children.push(heading1("Summary of the Invention"));
    children.push(bodyText(idea.proposedSolution));
  }

  // 4. Detailed Description
  if (idea.technicalApproach) {
    children.push(heading1("Detailed Description"));
    children.push(bodyText(idea.technicalApproach));
    if (idea.contradictionResolved) {
      children.push(heading2("Contradiction Resolved"));
      children.push(bodyText(idea.contradictionResolved));
    }
  }

  // 5. Claims
  if (idea.claimDraft) {
    children.push(heading1("Claims"));
    children.push(heading2("Method Claim"));
    children.push(bodyText(idea.claimDraft.methodClaim));
    children.push(heading2("System Claim"));
    children.push(bodyText(idea.claimDraft.systemClaim));
    children.push(heading2("Computer-Readable Medium Claim"));
    children.push(bodyText(idea.claimDraft.crmClaim));
    if (idea.claimDraft.notes) {
      children.push(heading2("Claim Notes"));
      children.push(bodyText(idea.claimDraft.notes));
    }
  }

  // 6. Abstract
  children.push(heading1("Abstract"));
  children.push(
    bodyText(
      `A ${idea.frameworkUsed !== "none" ? idea.frameworkUsed.toUpperCase() + "-derived " : ""}method and system for ${idea.title?.toLowerCase() || "the described invention"}. ${idea.proposedSolution?.substring(0, 300) || ""}`
    )
  );

  // Appendix A: Alice Analysis
  if (idea.aliceScore) {
    children.push(heading1("Appendix A: Alice/Section 101 Analysis"));
    children.push(bodyText(`Overall Score: ${idea.aliceScore.overallScore}/100`));
    children.push(bodyText(`Abstract Idea Risk: ${idea.aliceScore.abstractIdeaRisk}`));
    children.push(bodyText(`Analysis: ${idea.aliceScore.abstractIdeaAnalysis}`));
    children.push(bodyText(`Practical Application: ${idea.aliceScore.practicalApplication}`));
    children.push(bodyText(`Inventive Concept: ${idea.aliceScore.inventiveConcept}`));
    if (idea.aliceScore.recommendations?.length > 0) {
      children.push(heading2("Recommendations"));
      idea.aliceScore.recommendations.forEach((r: string) => children.push(bulletPoint(r)));
    }
  }

  // Appendix B: Inventive Step Analysis
  if (idea.inventiveStepAnalysis) {
    children.push(heading1("Appendix B: Inventive Step Analysis"));
    children.push(heading2("Primary Inventive Step"));
    children.push(bodyText(idea.inventiveStepAnalysis.primaryInventiveStep));
    if (idea.inventiveStepAnalysis.secondarySteps?.length > 0) {
      children.push(heading2("Secondary Inventive Steps"));
      idea.inventiveStepAnalysis.secondarySteps.forEach((s: string) =>
        children.push(bulletPoint(s))
      );
    }
    children.push(heading2("Non-Obviousness Argument"));
    children.push(bodyText(idea.inventiveStepAnalysis.nonObviousnessArgument));
    children.push(heading2("Technical Advantage"));
    children.push(bodyText(idea.inventiveStepAnalysis.technicalAdvantage));
  }

  // Appendix C: Market Analysis
  if (idea.marketNeedsAnalysis) {
    children.push(heading1("Appendix C: Market Needs Analysis"));
    children.push(bodyText(`Market Size: ${idea.marketNeedsAnalysis.marketSize}`));
    children.push(heading2("Target Segments"));
    idea.marketNeedsAnalysis.targetSegments.forEach((s: string) =>
      children.push(bulletPoint(s))
    );
    children.push(heading2("Pain Points Solved"));
    idea.marketNeedsAnalysis.painPointsSolved.forEach((p: string) =>
      children.push(bulletPoint(p))
    );
    children.push(heading2("Competitive Landscape"));
    children.push(bodyText(idea.marketNeedsAnalysis.competitiveLandscape));
    children.push(heading2("Commercialization Potential"));
    children.push(bodyText(idea.marketNeedsAnalysis.commercializationPotential));
    children.push(heading2("Strategic Value"));
    children.push(bodyText(idea.marketNeedsAnalysis.strategicValue));
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  return Packer.toBlob(doc);
}
